In [3]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[1, 2], [3, 4]]) 
b

array([[1, 2],
       [3, 4]])

In [6]:
zeros = np.zeros((2, 3)) 
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
arange = np.arange(0, 10, 2) 
arange

array([0, 2, 4, 6, 8])

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 2)

In [11]:
b.size

4

In [12]:
b.dtype

dtype('int32')

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[0, 1] 

2

In [16]:
a[:, 1]

array([2, 5])

In [17]:
a[1, :]

array([4, 5, 6])

In [20]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
a.reshape(2, 3)   

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [22]:
x+y

array([5, 7, 9])

In [23]:
x*y

array([ 4, 10, 18])